---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    #libvirt_uri: qemu+ssh://mars.devlab.sinenomine.net/system
    libvirt_uri: qemu:///system
    vm_name: m-instance-1

  tasks:
    - name: Shutdown instance
      virt:
        name: "{{ vm_name }}"
        state: destroyed
        uri: "{{ libvirt_uri }}"
      failed_when: false

    - name: Remove instance
      virt:
        name: "{{ vm_name }}"
        command: undefine
        uri: "{{ libvirt_uri }}"
      failed_when: false